### ISSUE TITLE
relationship with files-sync-stream

### ISSUE THREAD

**Issue by ghost** [derhuerst/avion#2]
Since I came across this project, I noticed that there was another repository related to this (files-sync-stream). I was wondering if we/I should give this any attention with the stage this program has grown to. Also, could you tell us what the difference is between the two?

Edit: My assumption is that `files-sync-stream` is the core that this relies on.

**Comment by derhuerst** [comment]
> My assumption is that `files-sync-stream` is the core that this relies on.

Correct! `files-sync-stream` is independent of the browser environment and does not care about files (only blobs of data) or transport; It only has the job to sync two (changing) sets of blobs/files.

> I was wondering if we/I should give this any attention [...].

If you're talking about general maintenance & fixing bugs: Any help is much appreciated! Currently, both mentioned projects are not my priority, but I'm willing to review & merge PRs.

**Comment by derhuerst** [comment]
I'm going to close this issue in favour of https://github.com/derhuerst/files-sync-stream/issues/4.
